#######################################
# Example MultiQC Configuration File
#######################################

# This file can be saved either in the MultiQC installation
# directory, or as ~/.multiqc_config.yaml

# Configuration settings are taken from the following locations, in order:
# - Hardcoded in MultiQC (multiqc/utils/config.py)
# - <installation_dir>/multiqc_config.yaml
# - ~/.multiqc_config.yaml
# - Command line options

# Note that all of the values below are set to the MultiQC defaults.
# It's recommended that you delete any that you don't need.

---
# Title to use for the report.
title: null

# Prepend sample names with their directory. Useful if analysing the
# sample samples with different parameters.
prepend_dirs: False

# Default output filenames
output_fn_name: ./output/multiqc_report.html
data_dir_name: ./output/multiqc_data

# Whether to create the parsed data directory in addition to the report
make_data_dir: True

# Cleaning options for sample names. Typically, sample names are detected
# from an input filename. If any of these strings are found, they and any
# text to their right will be discarded.
# For example - file1.fq.gz_trimmed.bam_deduplicated_fastqc.zip
# would be cleaned to 'file1'
# Two options here - fn_clean_exts will remove the defaults,
# extra_fn_clean_exts will append to the defaults
extra_fn_clean_exts:
    - .gz
    - .fastq
    - .fq
    - .bam
    - .sam
    - .sra
    - _tophat
    - _star_aligned
    - _fastqc
    - .alignment
    - .rmdup
    - type: remove
      pattern: '.sorted'
    - type: regex
      pattern: '^Sample_\d+'
    - type: regex_keep
      pattern: '[A-Z]{3}[1-9]{4}[A,B][1-9]'

# Ignore these files / directories / paths when searching for logs
fn_ignore_files:
    - .DS_Store
fn_ignore_dirs:
    - annoying_dirname
fn_ignore_paths:
    - '*/path/to/*_files/'

module_order:
  - featureCounts:
      name: "Featurecounts; Exonic assignment"
      anchor: "featurecounts_exonic"
      info: "Featurecounts mode: Assignment to exons"
      path_filters:
        - '*.exon.counts.txt.summary'
  - featureCounts:
      name: "Featurecounts; Genic assignment"
      anchor: "featurecounts_genic"
      info: "Featurecounts mode: Assignment to full gene length"
      path_filters:
        - '*.gene.counts.txt.summary'

report_section_order:
  featurecounts_exonic:
    before: featurecounts_genic

# Ignore files larger than this when searching for logs (bytes)
log_filesize_limit: 5000000

# MultiQC skips a couple of debug messages when searching files as the
# log can get very verbose otherwise. Re-enable here to help debugging.
report_readerrors: False
report_imgskips: False

# Opt-out of remotely checking that you're running the latest version
no_version_check: False

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False          # Try to use only flat image graphs
plots_force_interactive: False   # Try to use only interactive javascript graphs
plots_flat_numseries: 100        # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 50      # If interactive, don't plot on load if > this number of datasets
max_table_rows: 500              # Swap tables for a beeswarm plot above this

# Overwrite module filename search patterns. See multiqc/utils/search_patterns.yaml
# for the defaults. Remove a default by setting it to null.
sp:
    star:
        fn: '*Log.final.out'
    trimmomatic:
        contents: 'Trimmomatic'

# Specify a custom logo to add to reports (uncomment to use)
custom_logo: null         # '/home/ramaka02/resources/5775936.png'
custom_logo_url: null     # 'http://labs.neuroscience.mssm.edu/project/shen-lab/'
custom_logo_title: null   # 'Our Institute Name'
subtitle: null            # Grey text below title
intro_text: null          # Set to False to remove, or your own text

        

# Add generic information to the top of reports
report_header_info:
    - Want to know more?: 'See the <a href="http://multiqc.info/docs" target="_blank">MultiQC docs</a>'

# Overwrite the defaults of which table columns are visible by default
table_columns_visible:
    FastQC:
        percent_fails: False
        total_sequences: True

table_columns_name:
    Featurecounts; Exonic assignment:
        percent_assigned: "% Assigned Exonic"
        Assigned: "M Assigned Exonic"
    Featurecounts; Genic assignment:
        percent_assigned: "% Assigned Genic"
        Assigned: "M Assigned Genic"
    FastQC:
        percent_duplicates: "% Dups FastQC"
    Picard:
        PERCENT_DUPLICATION: "% Dups Picard"
